// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZrorKBoe7OkH1gIISaj1-lMTfjNY-FRI',
    appId: '1:102119003728:web:55d55b3231735ab7e6a355',
    messagingSenderId: '102119003728',
    projectId: 'turtle-soup-e7377',
    authDomain: 'turtle-soup-e7377.firebaseapp.com',
    storageBucket: 'turtle-soup-e7377.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtolLJ6fzhoBE4CUuy2iJ_tHF9PEosCq0',
    appId: '1:102119003728:android:1703233243579277e6a355',
    messagingSenderId: '102119003728',
    projectId: 'turtle-soup-e7377',
    storageBucket: 'turtle-soup-e7377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZgbEZ72fhB3HMxQdRKe9YlJ6ehzmjY2E',
    appId: '1:102119003728:ios:8697ffcfa719e8eae6a355',
    messagingSenderId: '102119003728',
    projectId: 'turtle-soup-e7377',
    storageBucket: 'turtle-soup-e7377.firebasestorage.app',
    iosBundleId: 'com.example.turtleSoup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZgbEZ72fhB3HMxQdRKe9YlJ6ehzmjY2E',
    appId: '1:102119003728:ios:8697ffcfa719e8eae6a355',
    messagingSenderId: '102119003728',
    projectId: 'turtle-soup-e7377',
    storageBucket: 'turtle-soup-e7377.firebasestorage.app',
    iosBundleId: 'com.example.turtleSoup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZrorKBoe7OkH1gIISaj1-lMTfjNY-FRI',
    appId: '1:102119003728:web:0b8a2811aad3b60fe6a355',
    messagingSenderId: '102119003728',
    projectId: 'turtle-soup-e7377',
    authDomain: 'turtle-soup-e7377.firebaseapp.com',
    storageBucket: 'turtle-soup-e7377.firebasestorage.app',
  );

}
