// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEdLAiSPYPCxqZEUC7GDmUu8z6k0X4QyY',
    appId: '1:417036717367:web:3f1230f9c98396a28f5eb2',
    messagingSenderId: '417036717367',
    projectId: 'turtle-soup-prod',
    authDomain: 'turtle-soup-prod.firebaseapp.com',
    storageBucket: 'turtle-soup-prod.firebasestorage.app',
    measurementId: 'G-DN882C784P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1jtTZVxOoLzbveDEj1CSUbRWCJ9K4x3E',
    appId: '1:417036717367:android:140c54f62f422b368f5eb2',
    messagingSenderId: '417036717367',
    projectId: 'turtle-soup-prod',
    storageBucket: 'turtle-soup-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9KqYYXNXQ4tMthFM96KqQ1NkpH9LGzLM',
    appId: '1:417036717367:ios:f78d3e1f40005a128f5eb2',
    messagingSenderId: '417036717367',
    projectId: 'turtle-soup-prod',
    storageBucket: 'turtle-soup-prod.firebasestorage.app',
    iosBundleId: 'com.example.turtleSoup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9KqYYXNXQ4tMthFM96KqQ1NkpH9LGzLM',
    appId: '1:417036717367:ios:f78d3e1f40005a128f5eb2',
    messagingSenderId: '417036717367',
    projectId: 'turtle-soup-prod',
    storageBucket: 'turtle-soup-prod.firebasestorage.app',
    iosBundleId: 'com.example.turtleSoup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEdLAiSPYPCxqZEUC7GDmUu8z6k0X4QyY',
    appId: '1:417036717367:web:29a1587bbe8b0a2a8f5eb2',
    messagingSenderId: '417036717367',
    projectId: 'turtle-soup-prod',
    authDomain: 'turtle-soup-prod.firebaseapp.com',
    storageBucket: 'turtle-soup-prod.firebasestorage.app',
    measurementId: 'G-CNRMQLSBN7',
  );
}
